### ISSUE TITLE
Use glyphspackage instead of glyphs file format

### ISSUE THREAD

**Issue by eweracs** [github/mona-sans#13]
Any reason Glyphs File Package is not used as a format? It's far better for version control, as each glyph is its own file, everything neatly separated into folders and thus much more clear where changes are made. Merging changes is thus far easier.

Only downside is it's only compatible with Glyphs 3+, not Glyphs 2.

**Comment by justinpenner** [comment]
The designer of Mona Sans is working in Glyphs 2.

![image](https://user-images.githubusercontent.com/46039243/201793789-9bb5a06c-b42e-47d6-b510-20806a8acf43.png)

**Comment by eweracs** [comment]
This has been fixed with the new 1.1 version.
