### ISSUE TITLE
Add to Google Web Fonts

### ISSUE THREAD

**Issue by benjamindenboer** [github/mona-sans#14]
Any plans to submit these? I’d love to be able to use these new typefaces in [Framer](https://www.framer.com/).

**Comment by applecuckoo** [comment]
There's an issue to add both Mona Sans and Hubot Sans, follow https://github.com/google/fonts/issues/5540 and https://github.com/google/fonts/issues/5541 respectively.

**Comment by tobiasahlin** [comment]
@benjamindenboer to answer your question, yes! We're working on adding them. (And @applecuckoo's is right, we're working on resolving these issues to get them in.) Let's keep this issue open until it's done 🙏

**Comment by hifocus** [comment]
Any updates to the addition?

**Comment by tobiasahlin** [comment]
It's been some time since this was filed, but we're actively working on this 🙏 will update this issue as we make progress.

**Comment by sailfuture** [comment]
Looking forward to using this beautiful font in 2024 👍

**Comment by ToddIndry37** [comment]
Any updates of both Mona & Hubot Sans to Google Fonts? Keep us updated!

**Comment by tobiasahlin** [comment]
@ToddIndry37 the Google fonts team preferred to push the launch until we've released v1.1 of both fonts, since we'll see some sweeping improvements and changes, including kerning and spacing adjustments. We're aiming to have v1.1 done in Q1, and the Google Fonts launch in late Q1 or Q2 (depending on the Google Fonts team pipeline 😌)

**Comment by ToddIndry37** [comment]
> @ToddIndry37 the Google fonts team preferred to push the launch until we've released v1.1 of both fonts, since we'll see some sweeping improvements and changes, including kerning and spacing adjustments. We're aiming to have v1.1 done in Q1, and the Google Fonts launch in late Q1 or Q2 (depending on the Google Fonts team pipeline 😌)

Ah alright. Let me know if you all planned to submit Mona & Hubot Sans to Google Fonts.

**Comment by rowe-morehouse** [comment]
Looking forward to this; I was trying to use Hubot in a Google Doc today, to no avail. Good luck w/ the process, @tobiasahlin!! 😎

**Comment by benjamindenboer** [comment]
This is now a reality! Thanks everyone.

**Comment by hifocus** [comment]
Yay!!

https://fonts.google.com/specimen/Mona+Sans
