### ISSUE TITLE
Improve kerning of AY pair in Mona Sans

### ISSUE THREAD

**Issue by danburzo** [github/mona-sans#15]
The AY pair has excessive space:

<img width="615" alt="the word Ayran typeset in Mona Sans" src="https://user-images.githubusercontent.com/205375/201666428-da49e3d3-49a8-4fb6-90fa-0423304d5c29.png">

**Comment by taryncowart** [comment]
@danburzo Are you seeing this issue in-use when typesetting? Looks good to me when actually in-use.
<img width="203" alt="Screen Shot 2022-11-14 at 10 48 35 AM" src="https://user-images.githubusercontent.com/99746865/201741407-7e8ff977-fe20-4d48-add3-8b8c4fa4b550.png">

**Comment by danburzo** [comment]
Oops, I meant to try that with the actual font but I got sidetracked. This was an issue on the presentation site on Chrome/macOS, will confirm shortly with the installed font.

**Comment by danburzo** [comment]
I am able to reproduce the issue with the installed font as well. This is Sketch on macOS 13, using `Mona-Sans.ttf` (variable) from the v1.0 release ZIP.

<img width="627" alt="Screenshot 2022-11-14 at 21 00 39" src="https://user-images.githubusercontent.com/205375/201743855-0e706294-6d81-42c7-941e-aec8e5ecb4ae.png">

<img width="252" alt="Screenshot 2022-11-14 at 21 01 39" src="https://user-images.githubusercontent.com/205375/201744010-baa43fb6-c51e-4f37-883a-9aca67acd903.png">

**Comment by eweracs** [comment]
Can you check in the latest exports from e2577d3d399af4e706c427a0ebaa5c121a3ec402? This is a new release and should have fixed a whole list of related issues.

**Comment by danburzo** [comment]
Looks good, thanks!
