### ISSUE TITLE
Misplaced umlauts in Chrome-based browsers

### ISSUE THREAD

**Issue by xTibor** [github/mona-sans#16]
I don't know if this is a browser or a font bug, however in Chrome-based browsers the font misplaces umlauts on the following characters: `ö` (U+00F6), `ü` (U+00FC), `Ö` (U+00D6), `Ü` (U+00DC).

**Examples:**

Vivaldi

![20221116_091712_Mona Sans   Hubot Sans - Vivaldi](https://user-images.githubusercontent.com/1627292/202128439-f5f85b22-3517-4174-8fc1-a79b780dcbb8.png)

Opera Mobile

![Screenshot_20221116-091404_Opera](https://user-images.githubusercontent.com/1627292/202128517-1e9cc812-6bfa-49bc-b945-93a7e477f4e9.png)

**Comment by justinpenner** [comment]
This has already been fixed. Try the latest release from the repo. The website is using a much older version of the font for some reason.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/46039243/202767438-24f4a607-28c1-4d50-ab30-8442b7639160.png">
Old (left) vs new (right)

**Comment by tobiasahlin** [comment]
Closing per @justinpenner's comment 🙏
