### ISSUE TITLE
Cover GF Latin Core glyphset and more

### ISSUE THREAD

**Issue by RosaWagner** [github/mona-sans#17]
As discussed in last meeting, here is the repository listing all the defined glyphsets for Google Fonts: [GF GLyphsets](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin)

We recommend to cover:
- GF Latin Core
- GF Latin Vietnamese
- GF Latin Plus

You can add this `.plist` file in the same directory as your Glyphs file, and in the font editor you would then see the list of glyphs that are already generated and the ones missing: 

[CustomFilterGF_Latin.plist.zip](https://github.com/github/mona-sans/files/10031450/CustomFilterGF_Latin.plist.zip)

<img width="494" alt="Capture d’écran 2022-11-17 à 13 29 46" src="https://user-images.githubusercontent.com/12222436/202446879-6e990c3e-1e4b-4ba4-9eb6-4cd6eb21bab0.png">

**Comment by erlandh** [comment]
I think this is the same issue, but just to add weight (ha) to the call for additional variable characters – in our case, macrons on all five vowels so it can be used for place names and Māori words in Aotearoa New Zealand. That would be amazing.
![mona-sans-macrons](https://user-images.githubusercontent.com/28126696/202579323-70adcfeb-104d-4187-805e-7a52de40d93a.png)

**Comment by tobiasahlin** [comment]
This is completed with the latest release 🎉
