### ISSUE TITLE
font-stretch doesn't work

### ISSUE THREAD

**Issue by Loremly** [github/mona-sans#22]
If I don't have Mona Sans locally installed on my computer, font-stretch does not work while developing a website. I defined the used values 75% - 125%, but none worked. I used the woff2 file, defined it in CSS, and tried linking it to the `<head>`, but failed both ways. What can I do?? Do I need to get every woff2 file and put it in my folder? or do I only need the main Mona Sans.woff2 file? Please and thank you

P.S: font-weight does work, just not font-stretch.

**Comment by Loremly** [comment]
I learned recently that Mona-Sans.woff2 is just mona-sans thin. I assumed it is because thats what the ttf file is. is that correct? am i just dumb?

**Comment by ottta** [comment]
@Loremly You did the correct way, Mona-Sans.ttf had bad test results based on fontbakery, one of them is style linking that causes trouble on css font-stretch. So you have to wait for the version to be fixed by the author, because public collaborators are not allowed to contribute yet, see #31

**Comment by h0m4m** [comment]
> If I don't have Mona Sans locally installed on my computer, font-stretch does not work while developing a website. I defined the used values 75% - 125%, but none worked. I used the woff2 file, defined it in CSS, and tried linking it to the `<head>`, but failed both ways. What can I do?? Do I need to get every woff2 file and put it in my folder? or do I only need the main Mona Sans.woff2 file? Please and thank you
> 
> P.S: font-weight does work, just not font-stretch.

experiencing this rn did u find a solution
