### ISSUE TITLE
ligature support

### ISSUE THREAD

**Issue by rexdivakar** [github/mona-sans#23]
Hi Folks, could someone please add ligature support for this font.

**Comment by tobiasahlin** [comment]
@rexdivakar We've got some minimal ligature support (e.g. `tt`) right now, but would love to add more. Any ligatures in particular that you would like to see added? 🙏

**Comment by rexdivakar** [comment]
I have been using Jetbrains mono on all my IDE and the ligature support is fantastic, please take a look at it and hope it would be a good sample.

https://www.jetbrains.com/lp/mono/

**Comment by crivotz** [comment]
This page in the specific https://www.jetbrains.com/lp/mono/#ligatures

**Comment by tobiasahlin** [comment]
We've added a bunch of ligatures in the latest release—I'm working on updating the documentation, but closing this out unless there are specific requests in addition to the ones that we've added.

**Comment by mayurankv** [comment]
I would love to see optional arrow ligatures i.e. `->`, `=>`, etc. and also ligatures for inequalities `>=`, `<=`, `==` and `===`
