### ISSUE TITLE
Conflicting font name

### ISSUE THREAD

**Issue by pera** [github/mona-sans#24]
Dear GitHub team,

The name you have chosen for your new font is quite confusing: [Mona](https://monafont.sourceforge.net/) is a well-known, culturally and historically important, font that has existed for more than two decades now. I would be rather surprised if you haven't heard of it before, but in case you haven't here is the Wikipedia article: https://en.wikipedia.org/wiki/Mona_(font)

It would be kind of you to change the name of your font to avoid confusion and even potential name collisions in the future.

Thanks very much

**Comment by tobiasahlin** [comment]
Thanks for your comment! The fonts currently coexist without any confusion that we are aware of, but if you learn of a case where it is occurring, please let us know 🙏
