### ISSUE TITLE
Variable font does not sit on the baseline properly

### ISSUE THREAD

**Issue by dwatracz** [github/mona-sans#26]
Variable font does not sit on the baseline properly. This makes aligning font to any box not looking visually balanced.

There is more space "above" the font, than "below it" (above the cap, than below the descender).

So when for example I design a button using Mona Sans Variable, it looks like the button label is too low, and should be higher.

This issue is not present in normal fonts, it is only in the variable font.

Below there is a screenshot explaining this situation (I'm using Sketch for design) with a variable version of the font and not variable, and there are significant differences between them.

![Screenshot 2022-12-06 at 12 15 14](https://user-images.githubusercontent.com/88429454/205897207-c29a4f3d-d994-426a-a19e-74ed0779e000.png)

**Comment by tobiasahlin** [comment]
Thank you for reporting @dwatracz ! This might get fixed in https://github.com/github/mona-sans/pull/9 - adding this reference as a reminder for me to circle back to it.

**Comment by tobiasahlin** [comment]
Fixed in https://github.com/github/mona-sans/pull/9 🙏 thank you @dwatracz !
