### ISSUE TITLE
Windows recognizes all font variations as Regular

### ISSUE THREAD

**Issue by YVVT** [github/mona-sans#27]
![image](https://user-images.githubusercontent.com/62426149/206154751-f9542fcb-5199-460e-afbc-18b230c8dd52.png)

**Comment by tobiasahlin** [comment]
@YtotheWT thank you for reporting—could you share some more details? 
- Which Windows version are you on?
- What app are you getting the screenshot from?
- Did you install the variable version, or the static version?

**Comment by YtotheWT** [comment]
1. Windows 11 22H2.
2. For different variants, should show corresponding variant names (like "Light Condensed", etc.).
3. Variable.

**Comment by tobiasahlin** [comment]
@YtotheWT thank you!

**Comment by YtotheWT** [comment]
Font preview in Windows Setting.

**Comment by juliandunn** [comment]
I confirm this is a problem, not just on Windows, but on Microsoft Word for macOS. Font Book on macOS seems to show all the variants, though.

<img width="653" alt="mona" src="https://user-images.githubusercontent.com/841412/206982502-cf481d79-76de-4918-b0c4-64f717689300.png">

**Comment by revodavid** [comment]
I observed the same issue when installing the single file "Mona Sans/Mona-Sans.ttf" from Settings > Personalization >Fonts. If I instead install the 48 TTF files in "Mona Sans/TTF", the font variations have the correct names in Windows.

**Comment by moi15moi** [comment]
This is happening because the font [Axis Value Tables](https://learn.microsoft.com/en-us/typography/opentype/spec/stat#axis-value-tables) is empty.

Windows/GDI create name from those Axis Value, so since it is empty, it give the default name which is regular to all of those [InstanceRecord](https://learn.microsoft.com/en-us/typography/opentype/spec/fvar#instancerecord)

**Comment by tobiasahlin** [comment]
Fixed in the PR referenced above 🙏 thank you all!
