### ISSUE TITLE
CSS Text Stroke issues with the Variable Font

### ISSUE THREAD

**Issue by jere-co** [github/mona-sans#32]
When creating a text stroke using the following CSS:

```CSS
h1 {
  color: black;
  -webkit-text-fill-color: white;
  -webkit-text-stroke-width: 1px;
  -webkit-text-stroke-color: black;
}
```

The font shows interesting strokes on some of the characters: 
![Screenshot 2022-12-20 at 16 48 57](https://user-images.githubusercontent.com/6527274/208694769-00c43e81-9be2-4d35-81c0-5f019e134129.png)

The issue is the clearest with the following: 
![Screenshot 2022-12-20 at 16 52 01](https://user-images.githubusercontent.com/6527274/208695415-f5a130ba-7889-428a-b41e-01057816f4c7.png)
![Screenshot 2022-12-20 at 16 50 04](https://user-images.githubusercontent.com/6527274/208695159-eee7dbe8-5550-478f-8ce4-a371e1c5d1d1.png)
![Screenshot 2022-12-20 at 16 50 10](https://user-images.githubusercontent.com/6527274/208695157-bd721500-ef85-4ae9-8135-584ccbfa1265.png)
![Screenshot 2022-12-20 at 16 50 14](https://user-images.githubusercontent.com/6527274/208695156-22af5307-95e5-4f8f-bd6d-367fe1354161.png)
![Screenshot 2022-12-20 at 16 50 20](https://user-images.githubusercontent.com/6527274/208695152-7d811171-dca6-4e8e-9544-00eacfee5c8d.png)
![Screenshot 2022-12-20 at 16 50 30](https://user-images.githubusercontent.com/6527274/208695147-81a8b0ab-3ccd-4185-8bd4-06416904cf54.png)

**Comment by tobiasahlin** [comment]
@jere-co I understand that this is frustrating! This is due to how the vector points are placed to optimize for the font's variability, and it's unlikely that this setup will change. I'll close this for now 🙏
