### ISSUE TITLE
≈ (approximately equal to) symbol bug

### ISSUE THREAD

**Issue by RandomMaerks** [github/mona-sans#33]
The two tilde symbols in the ≈ oscillate back and forth when interpolating between masters
The bug occurs in Mona Sans and Hubot Sans, variable and static.

https://user-images.githubusercontent.com/109415614/208702337-4b1ea0b1-af09-442d-85fb-c36cd70e0629.mov

![image](https://user-images.githubusercontent.com/109415614/208703825-c055785f-70ed-4563-9800-e13205238fac.png)

![image](https://user-images.githubusercontent.com/109415614/208703234-6a8d97ec-d395-4fac-bb39-1017604df6b1.png)

**Comment by tobiasahlin** [comment]
Thank you @RandomMaerks for finding and reporting! We're on it 🙏
