### ISSUE TITLE
Range of `ital` axis causing italics not rendering properly on Firefox

### ISSUE THREAD

**Issue by blueset** [github/mona-sans#42]
Mona Sans has the `ital` axis range set to 0 to 12, whereas the convention of `ital` axis ([MDN], [OpenType]), the range is set to 0 to 1.

Firefox uses `ital=1` on a variable font when CSS specifies `font-family: italic;`, which renders an almost illegible slant instead of the expected italic style.

<img width="458" alt="image" src="https://user-images.githubusercontent.com/553831/223935764-a2858c20-99cd-4464-9747-94bbd0eee368.png">

Similar issue: github/hubot-sans#10

[MDN]: https://developer.mozilla.org/en-US/docs/Web/CSS/font-style#variable_fonts
[OpenType]: https://learn.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_ital

**Comment by nchristopher** [comment]
Also having this issue. Would love to use Mona Sans on the web, but can't because it isn't cross browser compatible.

**Comment by ottta** [comment]
We have to wait for the pull request #9 :(

**Comment by Nurai1** [comment]
Closed in [#9 ](https://github.com/github/mona-sans/pull/9)
