### ISSUE TITLE
Uppercase 'i' and lowercase 'l' are indistinguishable

### ISSUE THREAD

**Issue by ffub** [github/mona-sans#44]
The uppercase 'i' nd lowercase 'L' are indistinguishable from each other. Best practice for accessibility is to avoid similarity between imposter letterforms:
https://medium.com/the-readability-group/a-guide-to-understanding-what-makes-a-typeface-accessible-and-how-to-make-informed-decisions-9e5c0b9040a0

Examples of how to create more contrast between L and i are:

![mona sans Il](https://github.com/github/mona-sans/assets/58170/422a8fee-5c9b-4913-bb2d-f8936bc19015)

* Use differing ascender heights (see Garnett)
* Add a tail to the L (see Work Sans)
* Add serifs to the i (see Space Grotesk stylistic alternate)
* Or do all three (see IBM Plex Sans)

**Comment by tobiasahlin** [comment]
@ffub thank you for opening this issue! We now have a few options of differentiating with some different style sets—see the readme 😌
