### ISSUE TITLE
Alternate double storey a

### ISSUE THREAD

**Issue by PionerJn** [github/mona-sans#52]
Would like to see this alternate spurless _a_ brought back as _ss0X_. There's vestiges of it in the variable ttf but can't seem to use it with the woff2. 
(Also the crossbar -middle horizontal line- would need a little tweaking and be slightly thinner.)

![image](https://github.com/github/mona-sans/assets/69699451/ef613362-faf9-4c88-aeda-9ca7a5797a41)

**Comment by PionerJn** [comment]
Is there any e.t.a. for v1.1?

**Comment by tobiasahlin** [comment]
@PionerJn We're targeting late December or early January 🙏 sorry for the wait! But we have a bunch of improvements coming in this area, so hopefully it'll be worth the wait.

**Comment by tobiasahlin** [comment]
@PionerJn it's back — added some documentation in the readme 😌

**Comment by PionerJn** [comment]
Is it back really? I don't see it 😌
