### ISSUE TITLE
Please provide usage documentation for font feature settings

### ISSUE THREAD

**Issue by Saeris** [github/mona-sans#53]
So, I just spent an afternoon digging away at how to get the stylistic alternates for the `a` and `g` characters to render in the browser. 

Using v1.0.1, first I mocked up a design in Figma, then used their handy VS Code plugin to get it's generated CSS to build out a page. What Figma gave me seemed to match up with CSS I was able to dig up in the Mona Sans microsite: `font-feature-settings: "salt" on;`

![image](https://github.com/github/mona-sans/assets/3144549/6703f69e-aefc-4e61-80cf-bd334a9335e5)

But on my own page, these alternates weren't rendering! After much digging I stumbled upon the solution thanks to this MDN article: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_fonts/OpenType_fonts_guide which linked me to a handy tool for extracting OpenType font feature properties: https://wakamaifondue.com/

![image](https://github.com/github/mona-sans/assets/3144549/c919d81e-8d90-467e-8962-e36310051340)

Turns out the correct CSS I needed was *actually* `font-feature-settings: "ss01" on;` instead!

So, I'm filing this issue both to help others who may have run into the same issue and couldn't find an answer, and to ask that official documentation be added for these and any other advanced font features that may require some uncommon CSS to enable.

Thanks for the font! It's pretty awesome!

**Comment by mgrn0** [comment]
Thanks for pointing this out, this helped me a lot!

**Comment by tobiasahlin** [comment]
Thank you for pointing this out! We just updated all stylistic sets—we now have eight (this will be added to the readme later today):

| Set | Description | Example |
| --- | --- | --- | 
| ss01 | Square diacritical marks (defaults to round) | ![ss01](https://github.com/user-attachments/assets/18fa3132-6839-4ef9-afd9-c75a082899ef) |
| ss02 | Wide uppercase I | ![ss02](https://github.com/user-attachments/assets/a0de7f9c-f9c0-4583-ac32-a10d25a54328) |
| ss03 | Lowercase l with tail | ![ss03](https://github.com/user-attachments/assets/8594effd-0528-4af9-8c58-0dfba66b2b45) |
| ss04 | Lowercase l with top serif | ![ss04](https://github.com/user-attachments/assets/7c7610a9-947e-45d5-80fc-71849a257d82) |
| ss05 | Double-storey a | ![ss05](https://github.com/user-attachments/assets/d31a11b8-1809-4a34-bbcb-b8b7057ddef0) |
| ss06 | Double-storey g | ![ss06](https://github.com/user-attachments/assets/ca8bef04-68d8-4c36-bfa6-8313d5642a9d) |
| ss07 | Round G | ![ss07](https://github.com/user-attachments/assets/4d5fb045-df90-4dc7-8dbb-3f2a271477df) |
| ss08 | Tabular zero with straight bar | ![ss08](https://github.com/user-attachments/assets/6c54f0eb-0054-4876-a366-1c00d955b89b) |

**Comment by tarikgraba** [comment]
No plan to update the release here: https://github.com/github/mona-sans/releases ?
