### ISSUE TITLE
Æ, Œ have odd proportions

### ISSUE THREAD

**Issue by eweracs** [github/mona-sans#58]
<img width="998" alt="image" src="https://github.com/github/mona-sans/assets/51919489/55c54a6c-7609-43da-aa42-12d6c8e916be">

**Comment by tobiasahlin** [comment]
Compare e.g. with San Francisco 

![Image](https://github.com/github/mona-sans/assets/211284/0f2d20a6-cf03-4460-b5cc-8596ad24ff8a)

**Comment by eweracs** [comment]
Verified as (somewhat oddly) completed in 2b2b35d11592b270c9944cbe8365ce3d017e17e0.
