### ISSUE TITLE
/notequal looks weird

### ISSUE THREAD

**Issue by eweracs** [github/mona-sans#62]
See https://github.com/github/hubot-sans/issues/17

<img width="722" alt="image" src="https://github.com/github/mona-sans/assets/51919489/34bbc8dd-e17f-456e-975a-3e4657d9b6a5">

**Comment by tobiasahlin** [comment]
I.e. ≠ shouldn't just be = with / stacked on top of it 👀

**Comment by eweracs** [comment]
Verified as completed in 2b2b35d11592b270c9944cbe8365ce3d017e17e0.
