### ISSUE TITLE
Missing stylistic set variants

### ISSUE THREAD

**Issue by eweracs** [github/mona-sans#68]
The following stylistic set glyphs are missing:
### ss01 (square dots)
Gdotaccent.ss01
Ldot.ss01
Zdotaccent.ss01
abrevedotbelow.ss01
acircumflexdotbelow.ss01
adotbelow.ss01
gdotaccent.ss01
idotaccent.ss01
ldot.ss01
zdotaccent.ss01
idotbelow.dotless.ss01
ldot.ss01.ss02
ldot.ss01.ss03
gdotaccent.ss01.ss05
periodcentered.ss01
periodcentered.loclCAT.ss01
periodcentered.loclCAT.case.ss01
bullet.ss01
### ss02 (serif l/I)
IJ.ss02
Ibreve.ss02
### ss04 (double-storey a)
abreve.ss04
ahookabove.ss04
amacron.ss04
### ss06 (proposed for legless G)
Gbreve.ss06
Gcaron.ss06
Gcircumflex.ss06

**Comment by tobiasahlin** [comment]
Fixed in https://github.com/github/mona-sans/pull/69 👀
