### ISSUE TITLE
'Ł' (U+0141) and 'ł' (U+0142) characters missing

### ISSUE THREAD

**Issue by michumk** [github/mona-sans#72]
The "Ł" & "ł" characters are missing in Mona Sans, but they're available in Hubot Sans.
As you can see on the screenshot, only Mona Sans is using fallback font for those two characters.

<img width="990" alt="Screenshot 2024-05-12 at 19 44 19" src="https://github.com/github/mona-sans/assets/35463079/951b4862-206b-47ed-9ceb-83c007376c80">

**Comment by eweracs** [comment]
Hello, this is fixed in an upcoming release. You can already find updated (preliminary) files in the v1.1 branch(es). Be aware that those files are subject to change and are not a reflection of a new release.
